#!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Rpi686 3.0 BETA 1"
TITLE="Rpi686-root"
MENU="Choose one of the following options:"

OPTIONS=(1 "Kali Linux"
         2 "Debian"
         3 "Ubuntu")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "Booting into Kali Linux as root..."
sudo chroot /home/pi/kali-rpi686/ /bin/su -l root
            ;;
        2)
            echo "Booting into Debian as root..."
sudo chroot /home/pi/debian-rpi686/ /bin/su -l root
            ;;
        3)
            echo "Booting into Ubuntu as root..."
sudo chroot /home/pi/ubuntu-rpi686/ /bin/su -l root
            ;;
esac
